spring:
  application:
    name: pessoas-backend

  datasource:
    url: jdbc:sqlserver://db:1433;databaseName=cadastro_pessoas;encrypt=false
    username: sa
    password: Cadastro@123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      initialization-fail-timeout: -1

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:sqlserver://db:1433;databaseName=cadastro_pessoas;encrypt=false
    user: sa
    password: Cadastro@123

  web:
    resources:
      add-mappings: false