spring:
  application:
    name: pessoas-backend

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=cadastro_pessoas;encrypt=false
    username: sa
    password: xxxxxx
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration